---
# Our taks to install some needed software
- name: link ruby
  file: src=/usr/local/rvm/rubies/ruby-1.9.3-p551/bin/ruby dest=/usr/bin/ruby state=link

# now install all packages we need
- name: install all needed packages
  yum: name={{ item }} update_cache=True
  with_items:
    - numactl
    - libaio
    - mutt
    - java
    - openssh-clients.x86_64