---
# This playbook deploys scaleio on a centos cluster

# First start with our common play to install some needed software
- name: deploy packages on all scaleio hosts
  hosts: scaleio
  gather_facts: no
  sudo: yes

  roles:
  - common