# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  # Now create three vm's name vagrant1..3
  # Each with different network redirect.
  config.vm.define "vagrant1" do | vagrant1 |
    vagrant1.vm.box = "puphpet/centos65-x64"    
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
    vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
    vagrant1.vm.network "private_network", type: "dhcp"
  end
  config.vm.define "vagrant2" do | vagrant2 |
    vagrant2.vm.box = "puphpet/centos65-x64"
    vagrant2.vm.network "forwarded_port", guest: 80, host: 8081
    vagrant2.vm.network "forwarded_port", guest: 443, host: 8444
    vagrant2.vm.network "private_network", type: "dhcp"
  end  
  config.vm.define "vagrant3" do | vagrant3 |
    vagrant3.vm.box = "puphpet/centos65-x64"
    vagrant3.vm.network "forwarded_port", guest: 80, host: 8082
    vagrant3.vm.network "forwarded_port", guest: 443, host: 8445
    vagrant3.vm.network "private_network", type: "dhcp"
  end
end
